version: "3.9"

services:
  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    env_file:
      - ./front-end/.env.production
    ports:
      - "5173:80"
    depends_on:
      - back-end
    networks:
      - restofy-net

  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    env_file:
      - ./back-end/.env.production
    ports:
      - "3001:3001"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - restofy-net

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    env_file:
      - ./notification-service/.env.production
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - restofy-net

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # RabbitMQ
      - "15672:15672" # Management UI
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - restofy-net

networks:
  restofy-net:
    driver: bridge